### ISSUE TITLE
Timings file generation

### ISSUE THREAD

**Issue by Clarauy** [IST-DASLab/spdy#2]
Hi, I wonder how the timings files under the timings folder are generated? Is the source code included in this repository? Because I find it nowhere. Thanks.

**Comment by efrantar** [comment]
Hi,

the timings were originally determined using the [`pruning_perf_sens_one_shot_iter()`](https://github.com/neuralmagic/sparseml/blob/b6b9f48ed3e8f2a0aeb8e5cb75ee250450dd4d03/src/sparseml/onnx/optim/sensitivity_pruning.py#L388) function in SparseML, followed by some model-specific post-processing to make sure that the model layers are properly matched up with the corresponding timings.

Unfortunately, when we developed SPDY (there may have been some improvements since then), this was not a very stable process and required different manual and SparseML/DeepSparse version-specific tweaks for different models to get right. Hence, we directly included our post-processed timing files.

I would recommend to try the function mentioned above and ask in the SparseML repository if you are having problems with matching up the timing outputs with the correct model layers.

Elias

**Comment by Clarauy** [comment]
> Hi,
> 
> the timings were originally determined using the [`pruning_perf_sens_one_shot_iter()`](https://github.com/neuralmagic/sparseml/blob/b6b9f48ed3e8f2a0aeb8e5cb75ee250450dd4d03/src/sparseml/onnx/optim/sensitivity_pruning.py#L388) function in SparseML, followed by some model-specific post-processing to make sure that the model layers are properly matched up with the corresponding timings.
> 
> Unfortunately, when we developed SPDY (there may have been some improvements since then), this was not a very stable process and required different manual and SparseML/DeepSparse version-specific tweaks for different models to get right. Hence, we directly included our post-processed timing files.
> 
> I would recommend to try the function mentioned above and ask in the SparseML repository if you are having problems with matching up the timing outputs with the correct model layers.
> 
> Elias

That helps. Thank you.
